<?php
	/**
	 * Do not edit this file directly.  You can copy this file to your theme directory
	 * in woocommerce-pay-per-post/expiration-status.php
	 *
     * $user_info = Array
(
    [last_purchase_date] => Carbon\Carbon Object
        (
            [date] => 2018-08-14 14:24:21.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [expiration_date] => Carbon\Carbon Object
        (
            [date] => 2023-11-14 14:24:21.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [time_remaining] => Array
        (
            [human] => 5 years from now
            [difference] => 62
            [frequency] => month
        )

)
	 */

?>
<div class="wc-ppp-expiration-status-container">
    <h4><?php esc_attr_e( 'Order Information', 'wc_pay_per_post' ); ?></h4>

    <ul>
	    <?php if(is_null($user_info['last_purchase_date'])): ?>
            <li><strong><?php esc_attr_e( 'Order Date', 'wc_pay_per_post' ); ?></strong>: <?php esc_attr_e( 'ADMIN OVERRIDE', 'wc_pay_per_post' ); ?></li>
            <li><strong><?php esc_attr_e( 'Expiration Date', 'wc_pay_per_post' ); ?></strong>: <?php esc_attr_e( 'NEVER', 'wc_pay_per_post' ); ?></li>
            <li><strong><?php esc_attr_e( 'Time Remaining', 'wc_pay_per_post' ); ?></strong>: &#8734;</li>

	    <?php else: ?>
        <li><strong><?php esc_attr_e( 'Order Date', 'wc_pay_per_post' ); ?></strong>: <?php echo $user_info['last_purchase_date']->toRfc850String(); ?></li>
        <li><strong><?php esc_attr_e( 'Expiration Date', 'wc_pay_per_post' ); ?></strong>: <?php echo $user_info['expiration_date']->toRfc850String(); ?></li>
        <li><strong><?php esc_attr_e( 'Time Remaining', 'wc_pay_per_post' ); ?></strong>: <?php echo $user_info['time_remaining']['human']; ?></li>
	    <?php endif; ?>
    </ul>
</div>
